version: "3"

services:
  video-maker:
    build:
      context: .
      dockerfile: main-cuda.Dockerfile
    env_file:
      - .env
    environment:
      - DEV=false
    ports:
      - "3123:3123"
    entrypoint: ["node", "dist/index.js"]
